export const langdata = {
  English: {
    lang: "English",
    greeting: "Welcome, ",
    inputprofile: "Please input your profile.",
    name_nickname: "Name / Nickname",
    name_rule_error: "Invalid name format.",
    team: "Team",
    team_rule_error: "Invalid team format.",
    others: "Other (hobbies, greetings, hometown, etc.)",
    others_rule_error: "Invalid format for other information.",
    your_image: "Your Image",
    submit: "Submit",
    submit_error: "Please enter something for Name, Team, Others, and image.",
    select_files: "Select files",
    profiles: "Profiles",
    delete: "Delete",
    submit_complete: "Registration complete! Reloading...",
    submit_fail: "Registration failed.",
    input_too_long: "Input is too long.",
    input_too_short: "Input is too short.",
    input_all: "Please fill in all fields.",
    mandatory: "Required",
    please_input_30: "Please enter within 30 characters.",
    please_input_300: "Please enter within 300 characters.",
    confirm: "Confirm",
    really_submit_question: "Are you sure you want to submit?",
    cancel: "Cancel",
    trimming: "Trimming",
    trimming_reset: "Reset trimming",
    file_choose: "File Select",
    Loading: "Loading",
    delete_confirmation: "Delete confirmation",
    really_delete_confirmation: "Are you sure you want to delete?",
    yes: "Yes",
    no: "No",
    delete_complete: "Deleted! Reloading!",
    delete_user: "Delete user",
    donot_input_blankonly: "Blank input is not allowed",
    submitting: "Submitting",
    forget_pass: "Forget Password?",
    or: "or",
    Log_in: "Log in",
    Log_out: "Log out",
    Sign_up: "Sign up",
    User_name: "User name",
    You: " (You)",
    Email_address: "E-mail address",
    Password: "Password",
    ConfirmPassword: "Re-input Password",
    Back: "< Back",
    Invalid_email_format: "Incorrect e-mail format",
    Invalid_pass_format: "Incorrect password format",
    Invalid_confirmpass_format: "Please match password",
    Invalid_format_error: "Please confirm error shown screen",
    Redirect_to_login: "You need to login first",
    Login_fail: "Email or Password is incorrect",
    Profile_input: "Profile Input",
    Signup_complete: "Signup completed! Redirect to homepage...",
    Jump_profiles: "View profiles",
    Jump_Profile_Submit: "Edit your profile",
    No_profile_result:
      "There are no profiles in your team. Please add your profile first.",
  },
  Japanese: {
    lang: "日本語",
    greeting: "ようこそ、",
    inputprofile: "あなたのプロフィールを入力してください。",
    name_nickname: "名前 / ニックネーム",
    name_rule_error: "無効な名前の形式です。",
    team: "チーム",
    team_rule_error: "無効なチームの形式です。",
    others: "その他（趣味、挨拶、出身地など）",
    others_rule_error: "その他の情報の形式が無効です。",
    your_image: "あなたの画像",
    submit: "提出する",
    submit_error: "名前、チーム、その他、画像に何かを入力してください。",
    select_files: "ファイルを選択する",
    profiles: "プロフィール",
    delete: "削除する",
    submit_complete: "登録完了！リロード中...",
    submit_fail: "登録に失敗しました。",
    input_too_long: "入力が長すぎます。",
    input_too_short: "入力が短すぎます。",
    input_all: "すべてのフィールドを入力してください。",
    mandatory: "必須",
    please_input_30: "30文字以内で入力してください。",
    please_input_300: "300文字以内で入力してください。",
    confirm: "確認する",
    really_submit_question: "本当に提出しますか？",
    cancel: "キャンセル",
    trimming: "トリミング",
    trimming_reset: "トリミングをリセット",
    file_choose: "ファイル選択",
    Loading: "読み込み中",
    delete_confirmation: "削除の確認",
    really_delete_confirmation: "本当に削除しますか？",
    yes: "はい",
    no: "いいえ",
    delete_complete: "削除しました！リロード中...",
    delete_user: "ユーザーを削除する",
    donot_input_blankonly: "空白のみの入力は許可されていません",
    submitting: "提出中",
    forget_pass: "パスワードを忘れましたか？",
    or: "または",
    Log_in: "ログイン",
    Log_out: "ログアウト",
    Sign_up: "サインアップ",
    User_name: "ユーザー名",
    You: "（あなた）",
    Email_address: "メールアドレス",
    Password: "パスワード",
    ConfirmPassword: "パスワードを再入力",
    Back: "< 戻る",
    Invalid_email_format: "無効なメールの形式です",
    Invalid_pass_format: "無効なパスワードの形式です",
    Invalid_confirmpass_format: "パスワードが一致していません",
    Invalid_format_error: "エラー表示画面を確認してください",
    Redirect_to_login: "最初にログインする必要があります",
    Login_fail: "メールまたはパスワードが間違っています",
    Profile_input: "プロフィール入力",
    Signup_complete:
      "サインアップが完了しました！ホームページにリダイレクトします...",
    Jump_profiles: "プロフィールを表示",
    Jump_Profile_Submit: "プロフィールを編集",
    No_profile_result:
      "あなたのチームにはプロフィールがありません。最初にプロフィールを追加してください。",
  },
  Chinese: {
    lang: "中文",
    greeting: "欢迎，",
    inputprofile: "请输入您的个人资料。",
    name_nickname: "姓名 / 昵称",
    name_rule_error: "无效的姓名格式。",
    team: "团队",
    team_rule_error: "无效的团队格式。",
    others: "其他（爱好、问候、家乡等）",
    others_rule_error: "其他信息的格式无效。",
    your_image: "您的头像",
    submit: "提交",
    submit_error: "请为姓名、团队、其他和图像输入内容。",
    select_files: "选择文件",
    profiles: "个人资料",
    delete: "删除",
    submit_complete: "注册完成！重新加载...",
    submit_fail: "注册失败。",
    input_too_long: "输入太长。",
    input_too_short: "输入太短。",
    input_all: "请填写所有字段。",
    mandatory: "必填",
    please_input_30: "请输入30个字符以内。",
    please_input_300: "请输入300个字符以内。",
    confirm: "确认",
    really_submit_question: "您确定要提交吗？",
    cancel: "取消",
    trimming: "修剪",
    trimming_reset: "重置修剪",
    file_choose: "文件选择",
    Loading: "加载中",
    delete_confirmation: "删除确认",
    really_delete_confirmation: "您确定要删除吗？",
    yes: "是",
    no: "否",
    delete_complete: "已删除！重新加载！",
    delete_user: "删除用户",
    donot_input_blankonly: "不允许输入空白",
    submitting: "提交中",
    forget_pass: "忘记密码？",
    or: "或",
    Log_in: "登录",
    Log_out: "退出",
    Sign_up: "注册",
    User_name: "用户名",
    You: "（您）",
    Email_address: "电子邮件地址",
    Password: "密码",
    ConfirmPassword: "重新输入密码",
    Back: "< 返回",
    Invalid_email_format: "电子邮件格式不正确",
    Invalid_pass_format: "密码格式不正确",
    Invalid_confirmpass_format: "请匹配密码",
    Invalid_format_error: "请确认显示的错误屏幕",
    Redirect_to_login: "您需要先登录",
    Login_fail: "电子邮件或密码不正确",
    Profile_input: "个人资料输入",
    Signup_complete: "注册完成！重定向到主页...",
    Jump_profiles: "查看个人资料",
    Jump_Profile_Submit: "编辑您的个人资料",
    No_profile_result: "您的团队中没有个人资料。请先添加您的个人资料。",
  },
  Hindi: {
    lang: "हिन्दी",
    greeting: "स्वागत है, ",
    inputprofile: "कृपया अपनी प्रोफ़ाइल दर्ज करें।",
    name_nickname: "नाम / उपनाम",
    name_rule_error: "अमान्य नाम प्रारूप।",
    team: "टीम",
    team_rule_error: "अमान्य टीम प्रारूप।",
    others: "अन्य (शौक, शुभकामनाएँ, गृहनगर, आदि)",
    others_rule_error: "अन्य जानकारी के लिए अमान्य प्रारूप।",
    your_image: "आपकी छवि",
    submit: "प्रस्तुत",
    submit_error: "कृपया नाम, टीम, अन्य और छवि के लिए कुछ दर्ज करें।",
    select_files: "फ़ाइलें चुनें",
    profiles: "प्रोफ़ाइल",
    delete: "हटाएं",
    submit_complete: "पंजीकरण पूरा हुआ! पुनः लोड हो रहा है...",
    submit_fail: "पंजीकरण विफल हुआ।",
    input_too_long: "इनपुट बहुत लंबा है।",
    input_too_short: "इनपुट बहुत छोटा है।",
    input_all: "कृपया सभी फ़ील्ड भरें।",
    mandatory: "अनिवार्य",
    please_input_30: "कृपया 30 वर्णों के भीतर दर्ज करें।",
    please_input_300: "कृपया 300 वर्णों के भीतर दर्ज करें।",
    confirm: "पुष्टि करें",
    really_submit_question: "क्या आप वाकई प्रस्तुत करना चाहते हैं?",
    cancel: "रद्द करें",
    trimming: "ट्रिमिंग",
    trimming_reset: "ट्रिमिंग रीसेट करें",
    file_choose: "फ़ाइल चुनें",
    Loading: "लोड हो रहा है",
    delete_confirmation: "हटाने की पुष्टि",
    really_delete_confirmation: "क्या आप वाकई हटाना चाहते हैं?",
    yes: "हाँ",
    no: "नहीं",
    delete_complete: "हटा दिया गया! पुनः लोड हो रहा है!",
    delete_user: "उपयोगकर्ता हटाएं",
    donot_input_blankonly: "खाली इनपुट अनुमति नहीं है",
    submitting: "प्रस्तुत कर रहा है",
    forget_pass: "पासवर्ड भूल गए?",
    or: "या",
    Log_in: "लॉग इन करें",
    Log_out: "लॉग आउट",
    Sign_up: "साइन अप करें",
    User_name: "उपयोगकर्ता नाम",
    You: " (आप)",
    Email_address: "ईमेल पता",
    Password: "पासवर्ड",
    ConfirmPassword: "पासवर्ड दुबारा दर्ज करें",
    Back: "< वापस",
    Invalid_email_format: "गलत ईमेल प्रारूप",
    Invalid_pass_format: "गलत पासवर्ड प्रारूप",
    Invalid_confirmpass_format: "कृपया पासवर्ड मिलाएं",
    Invalid_format_error: "कृपया स्क्रीन पर दिखाए गए त्रुटि की पुष्टि करें",
    Redirect_to_login: "पहले लॉगिन करने की आवश्यकता है",
    Login_fail: "ईमेल या पासवर्ड गलत है",
    Profile_input: "प्रोफ़ाइल इनपुट",
    Signup_complete: "साइनअप पूरा हुआ! होमपेज पर रीडायरेक्ट हो रहा है...",
    Jump_profiles: "प्रोफ़ाइल देखें",
    Jump_Profile_Submit: "अपनी प्रोफ़ाइल संपादित करें",
    No_profile_result:
      "आपकी टीम में कोई प्रोफ़ाइल नहीं है। कृपया पहले अपनी प्रोफ़ाइल जोड़ें।",
  },
};
