export const langdata = {
	English: {
		lang: "English",
		greeting: "Welcome, QA Team!",
		inputprofile: "Please input your profile.",
		name_nickname: "Name / Nickname",
		name_rule_error: "Invalid name format.",
		team: "Team",
		team_rule_error: "Invalid team format.",
		others: "Other (hobbies, greetings, hometown, etc.)",
		others_rule_error: "Invalid format for other information.",
		your_image: "Your Image",
		submit: "Submit",
		submit_error: "Please enter something for Name, Team, Others, and image.",
		select_files: "Select files",
		profiles: "Profiles",
		delete: "Delete",
		submit_complete: "Registration complete! Reloading...",
		submit_fail: "Registration failed.",
		input_too_long: "Input is too long.",
		input_too_short: "Input is too short.",
		input_all: "Please fill in all fields.",
		mandatory: "Required",
		please_input_30: "Please enter within 30 characters.",
		please_input_300: "Please enter within 300 characters.",
		confirm: "Confirm",
		really_submit_question: "Are you sure you want to submit?",
		cancel: "Cancel",
		trimming: "Trimming",
		trimming_reset: "Reset trimming",
		file_choose: "File Select",
		Loading: "Loading",
		delete_confirmation: "Delete confirmation",
		really_delete_confirmation: "Are you sure you want to delete?",
		yes: "Yes",
		no: "No",
		delete_complete: "Deleted! Reloading!",
		donot_input_blankonly: "Blank input is not allowed",
		submitting: "Submitting",
		forget_pass: "Forget Password?",
		or: "or",
		Log_in: "Log in",
		Sign_up: "Sign up",
		User_name: "User name",
		Email_address: "E-mail address",
		Password: "Password",
		ConfirmPassword: "Re-input Password",
		Back: "< Back",
		Invalid_email_format: "Incorrect e-mail format",
		Invalid_pass_format: "Incorrect password format",
		Invalid_confirmpass_format: "Please match password",
		Invalid_format_error: "Please confirm error shown screen",
		Redirect_to_login: "You need to login first",
		Login_fail: "Email or Password is incorrect",
		Profile_input: "Profile Input",
		Signup_complete: "Signup completed! Redirect to homepage...",
		Jump_profiles: "View profiles",
		Jump_Profile_Submit: "Edit your profile",
		No_profile_result:
			"There are no profiles in your team. Please add your profile first.",
	},
	Japanese: {
		lang: "Japanese",
		greeting: "ようこそ！ QAの皆さん！",
		inputprofile: "あなたのプロファイルを入力してください！",
		name_nickname: "名前 / ニックネーム",
		name_rule_error: "名前の形式が正しくありません",
		team: "チーム",
		team_rule_error: "チームの形式が正しくありません",
		others: "その他(趣味、挨拶、出身地等)",
		others_rule_error: "その他の形式が正しくありません",
		your_image: "画像ファイル",
		submit: "送信",
		submit_error: "Name, Team, Others, imageには何か入力してください",
		select_files: "ファイルを選択",
		profiles: "プロフィール",
		delete: "削除",
		submit_complete: "登録しました！リロードします！",
		submit_fail: "登録が失敗しました。",
		input_too_long: "長すぎる入力があります",
		input_all: "すべて入力してください",
		mandatory: "必須",
		please_input_30: "30文字以内で入力してください",
		please_input_300: "300文字以内で入力してください",
		confirm: "確認",
		really_submit_question: "本当に送信しますか？",
		cancel: "キャンセル",
		trimming: "トリミング",
		trimming_reset: "トリミングをリセット",
		file_choose: "ファイル選択",
		Loading: "読み込み中",
		delete_confirmation: "削除確認",
		really_delete_question: "本当に削除しますか？",
		yes: "はい",
		no: "いいえ",
		delete_complete: "削除しました！リロードします！",
		donot_input_blankonly: "空白のみの入力はできません",
		submitting: "送信中",
	},
	Chinese: {
		lang: "中文",
		greeting: "欢迎！QA团队成员！",
		inputprofile: "请输入您的个人资料！",
		name_nickname: "姓名 / 昵称",
		name_rule_error: "无效的姓名格式",
		team: "团队",
		team_rule_error: "无效的团队格式",
		others: "其他(爱好、问候、家乡、等)",
		others_rule_error: "无效的其他格式",
		your_image: "您的图片",
		submit: "提交",
		submit_error: "Name, Team, Others, image请输入信息。",
		select_files: "选择文件",
		profiles: "档案",
		delete: "刪除",
		submit_complete: "注册完成！正在重新加载...",
		submit_fail: "注册失败。",
		input_too_long: "输入太长。",
		input_all: "请填写所有字段。",
		mandatory: "必填",
		please_input_30: "请输入不超过30个字符。",
		please_input_300: "请输入不超过300个字符。",
		confirm: "确认",
		really_submit_question: "确定要提交吗？",
		cancel: "取消",
		trimming: "裁剪",
		trimming_reset: "重置裁剪",
		file_choose: "选择文件",
		Loading: "加载中",
		delete_confirmation: "删除确认",
		really_delete_confirmation: "确定要删除吗？",
		yes: "是",
		no: "否",
		delete_complete: "已删除！重新加载！",
		donot_input_blankonly: "不允许空白输入",
		submitting: "提交中",
	},
	Hindi: {
		lang: "हिन्दी",
		greeting: "नमस्ते!! क्यूए टीम के सदस्यों!!",
		inputprofile: "कृपया अपनी प्रोफ़ाइल दर्ज करें!!",
		name_nickname: "नाम / उपनाम",
		name_rule_error: "अमान्य नाम प्रारूप",
		team: "टीम",
		team_rule_error: "अमान्य टीम प्रारूप",
		others: "अन्य (रुचि, अभिवादन, जन्म स्थान, आदि)",
		others_rule_error: "अमान्य अन्य प्रारूप",
		your_image: "आपकी छवि",
		submit: "प्रस्तुत करें",
		submit_error: "Name, Team, Others, image कुछ भी दर्ज करें।",
		select_files: "फ़ाइल का चयन करें ",
		profiles: "प्रोफ़ाइल",
		delete: "मिटाएँ",
		submit_complete: "पंजीकरण पूरा हुआ! दोबारा लोड हो रहा है...",
		submit_fail: "पंजीकरण विफल हुआ।",
		input_too_long: "इनपुट बहुत लंबा है।",
		input_all: "कृपया सभी फ़ील्ड भरें।",
		mandatory: "अनिवार्य",
		please_input_30: "कृपया 30 अक्षरों के अंदर दर्ज करें।",
		please_input_300: "कृपया 300 अक्षरों के अंदर दर्ज करें।",
		confirm: "पुष्टि करें",
		really_submit_question: "क्या आप सचमुच प्रस्तुत करना चाहते हैं?",
		cancel: "रद्द करें",
		trimming: "ट्रिमिंग",
		trimming_reset: "ट्रिमिंग रीसेट करें",
		file_choose: "फ़ाइल चुनें",
		Loading: "लोड हो रहा है",
		delete_confirmation: "हटाने की पुष्टि",
		really_delete_confirmation: "क्या आप सचमुच हटाना चाहते हैं?",
		yes: "हां",
		no: "नहीं",
		delete_complete: "हटा दिया गया! पुनः लोड हो रहा है!",
		donot_input_blankonly: "खाली इनपुट अनुमति नहीं है।",
		submitting: "सबमिट कर रहा है",
	},
};
